小黑盒图标明显有问题
BetterAndroid/android-notification-icon-project pull request #225
Opened 2022-11-14 00:51 UTC by NekoMua

我给换回去了

2022-11-14 01:07 UTC, fankes requested changes
请重新格式化代码

2022-11-14 01:18 UTC, NekoMua commented
> 请重新格式化代码

应该修改了

2022-11-14 05:12 UTC, fankes approved these changes

2022-11-14 05:13 UTC, merged

2022-11-15 05:58 UTC, piscesmk2013 commented
小黑盒图标有啥问题？不上传任何图片或者详细说明就随意还原？审查太松散了吧？

![微信图片_20221115135614](https://user-images.githubusercontent.com/4004730/201837679-feefa187-ca91-4e2c-ba10-7ef11e306e1f.jpg)

2022-11-15 06:58 UTC, NekoMua commented
> 小黑盒图标有啥问题？不上传任何图片或者详细说明就随意还原？审查太松散了吧？
> 
> ![微信图片_20221115135614](https://user-images.githubusercontent.com/4004730/201837679-feefa187-ca91-4e2c-ba10-7ef11e306e1f.jpg)
> 

白图标加白底，你去看看，然后就是图标改的太小了吧🤔![Screenshot_2022-11-15-14-56-53-491-edit_com.fankes.notifyicondebugging.jpg](https://user-images.githubusercontent.com/59407295/201850857-5e386e74-2954-41d4-908c-27f4b6dd8126.jpg)![Screenshot_2022-11-15-14-57-24-187-edit_com.github.android.jpg](https://user-images.githubusercontent.com/59407295/201850865-8e0568ef-e58c-4f4a-8da5-11f797b840b7.jpg)

2022-11-15 08:22 UTC, piscesmk2013 commented
并没有任何问题   而且图标也是标准的72*72  直接从apk里解包出来的   不过看到你的截图我知道了  不同系统对于这个图标色彩的解析问题，我之所以将iconColor改为白色是因为之前的黑色在A13类原生ROM使用深色模式时几乎与QS背景融为一体了  不好看
![微信截图_20221115161754](https://user-images.githubusercontent.com/4004730/201866195-6a13f329-ba62-4f95-8abe-0cf9c2f57576.png)

2022-11-15 08:45 UTC, NekoMua commented
> 并没有任何问题   而且图标也是标准的72*72  直接从apk里解包出来的   不过看到你的截图我知道了  不同系统对于这个图标色彩的解析问题，我之所以将iconColor改为白色是因为之前的黑色在A13类原生ROM使用深色模式时几乎与QS背景融为一体了  不好看
> ![微信截图_20221115161754](https://user-images.githubusercontent.com/4004730/201866195-6a13f329-ba62-4f95-8abe-0cf9c2f57576.png)
> 

难怪呢😂😂，那我也不知道改怎么修改了，黑色背景在类原生会出问题，白色背景又会在MIUI上出问题

2022-11-15 08:51 UTC, NekoMua commented
> 并没有任何问题   而且图标也是标准的72*72  直接从apk里解包出来的   不过看到你的截图我知道了  不同系统对于这个图标色彩的解析问题，我之所以将iconColor改为白色是因为之前的黑色在A13类原生ROM使用深色模式时几乎与QS背景融为一体了  不好看
> ![微信截图_20221115161754](https://user-images.githubusercontent.com/4004730/201866195-6a13f329-ba62-4f95-8abe-0cf9c2f57576.png)
> 

那要不你去换个737375，那个好像还可以，我比较忙😂