使命召唤手游通知图标添加
BetterAndroid/android-notification-icon-project pull request #368
Opened 2023-07-20 10:54 UTC by 09277632

增加的 APP 名称：使命召唤手游
图标用途：通知图标修复
测试图：![image](https://github.com/09277632/photo/blob/main/_cgi-bin_mmwebwx-bin_webwxgetmsgimg__%26MsgID%3D8208843056945180170%26skey%3D%40crypt_7e40e407_1be8abb03110ced4916ac96e864da7ae%26mmweb_appid%3Dwx_webfilehelper.png)

2023-07-20 18:40 UTC, fankes commented
测试图无法查看

2023-07-20 18:42 UTC, fankes requested changes
json 格式错误

2023-07-21 00:48 UTC, 09277632 commented
![Screenshot_2023-07-21-08-32-54-618_com fankes notifyicondebugging](https://github.com/fankes/AndroidNotifyIconAdapt/assets/103803785/8612eef0-a759-43ad-8127-6d0fe0bf7de9)
@fankes 抱歉刚误上传了两个推送请求，你直接看最新的就行。

2023-07-21 03:25 UTC, fankes approved these changes

2023-07-21 03:26 UTC, merged