新增 智能助理
BetterAndroid/android-notification-icon-project pull request #498
Opened 2024-08-10 14:40 UTC by XCwosjw

新版本智能助理的"出行助手"功能会推送“焦点通知”，例如航班信息和火车信息，从而让通知栏出现智能助理的图标。该PR增加了符合 Android 通知图标规范的智能助理通知图标。

2024-08-11 00:14 UTC, fankes commented
格式和缩进有问题，请重新整改

2024-08-11 00:15 UTC, fankes requested changes
格式和缩进有问题，请重新整改

2024-08-11 02:10 UTC, Illustar0 commented
已整改

2024-08-11 16:32 UTC, fankes requested changes
依然有问题，你可否在改之前看一下之前的缩进是 2 spaces

2024-08-12 00:56 UTC, Illustar0 commented
说起来你可能不信，但我也不知道他怎么变成了那个样子。第二个commit就应该对齐了才对？怪欸

2024-08-13 04:02 UTC, fankes approved these changes

2024-08-13 04:02 UTC, fankes commented
会不会是你的浏览器开了奇怪的插件，应该用客户端提交

2024-08-13 04:02 UTC, merged